export * from './catalog-page';
export * from './not-found-page';
export * from './cart-page';
export * from './product-page';
export * from './favorites-page';
export * from './register-page';
export * from './login-page';
export * from './reset-password-page';
export * from './forgot-password-page';