export { CatalogPage } from "./catalog-page";
export { NotFoundPage } from "./not-found-page";
export { CartPage } from "./cart-page";
// export * from './product-page';
export { FavoritesPage } from "./favorites-page";
export { RegisterPage } from "./register-page";
export { LoginPage } from "./login-page";
export { ProductPage } from "./product-page";
export { ResetPasswordPage } from "./reset-password-page";
export { ForgotPasswordPage } from "./forgot-password-page";
