export const ROUTES = {
  HOME: "/",
  CATALOG: "/catalog",
  CATALOG_LOT: (lotId: string) => `/catalog/${lotId}`,
  MY_BIDS: "/my-bids",
  FAVORITES: "/favorites",
  PROFILE: "/profile",
  PROFILE_SELLER_PANEL: "/profile/seller-panel",
  PROFILE_BIDS_HISTORY: "/profile/bids-history",
  PROFILE_MY_LOTS: "/profile/my-lots",
  CREATE_PRODUCT: "/create-product",
  REGISTER: "/register",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  NOT_FOUND: "*",
} as const;
