export const ROUTES = {
  HOME: "/",
  CATALOG: "/catalog",
  CATALOG_PRODUCT: (productId: string) => `/catalog/${productId}`,
  MY_BIDS: "/my-bids",
  FAVORITES: "/favorites",
  PROFILE: "/profile",
  PROFILE_SELLER_PANEL: "/profile/seller-panel",
  PROFILE_BIDS_HISTORY: "/profile/bids-history",
  REGISTER: "/register",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  NOT_FOUND: "*",
} as const;
